version: 2
project_name: mcp-box

builds:
  - env:
      - CGO_ENABLED=0
    dir: ./src/go
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    main: ./main.go
    binary: mcp-box
    hooks:
      pre:
        - go mod tidy

archives:
  - format: binary
    name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}"
